### ISSUE TITLE
[LDJ-010-20240507] Cursor Lock not working

### ISSUE THREAD

**Issue by ASleepyCat** [two-torial/sp2xpatcher#2]
Using patch file `LDJ-662a05c7_a5bf9c.json`.
Other patches like timer freezes and song start delay work fine.

[log.txt](https://github.com/user-attachments/files/16066201/log.txt)

**Comment by akitakedits** [comment]
Looking into it

**Comment by akitakedits** [comment]
I've confirmed this doesn't seem to work in game, the cursor goes back to the folder root instead of staying on the previously selected song.

Hex patch seemed okay at first though which is odd, so I went to check in IDA and realized the offset used was a false-positive, found another instance of similar pseudocode, tested a patch at that offset, and it works.

Fixed with https://github.com/two-torial/sp2xpatcher/commit/fa121a85d66cc2a5162deaf8cbf7bcb4abe2f890
